version: '3.7'

services:
  #
  # ---- Balancer service and related ----
  balancer-service:
    build: './balancer/service'
    depends_on:
      - aggregator-service
    ports:
      - 80:80
      - 443:443
    networks:
      - services

  #
  # ---- Aggregator service and related ----
  aggregator-service:
    build: ./aggregator/service
    depends_on:
      - recipe-service
      - token-service
      - user-service
    volumes:
      - ./scripts:/opt
    networks:
      - services

  #
  # ---- Recipe service and related ----
  recipe-service:
    build: ./recipe/service
    depends_on:
      - recipe-cache
      - recipe-database
    volumes:
      - ./scripts:/opt
    links:
      - recipe-cache:cache
      - recipe-database:database
    networks:
      - services
      - recipe-service
  
  recipe-cache:
    image: redis:5.0.7
    volumes:
      - './recipe/cache:/data'
    restart: always
    networks:
      - recipe-service

  recipe-database:
    image: mysql:5.7.28
    volumes:
      - './recipe/database:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - recipe-service
  
  #
  # ---- User service and related ----
  user-service:
    build: ./user/service
    depends_on:
      - token-service
      - user-cache
      - user-database
    volumes:
      - ./scripts:/opt
    links:
      - user-cache:cache
      - user-database:database
    networks:
      - services
      - user-service
  
  user-cache:
    image: redis:5.0.7
    volumes:
      - './user/cache:/data'
    restart: always
    networks:
      - user-service

  user-database:
    image: mysql:5.7.28
    volumes:
      - './user/database:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gluten
      MYSQL_USER: gluten
      MYSQL_PASSWORD: gluten
    networks:
      - user-service
  
  #
  # ---- Token service and related ----
  token-service:
    build: ./token/service
    volumes:
      - ./scripts:/opt
    networks:
      - services
      - token-service

networks:
  services:
  user-service:
  recipe-service:
  token-service:
