version: '3.7'

services:
  #
  # ---- Aggregator service and related ----
  aggregator-service:
    build: ./aggregator/service
    container_name: aggregator-service
    depends_on:
      - recipe-service
      - user-service
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./scripts:/opt
    networks:
      - services

  #
  # ---- Recipe service and related ----
  recipe-service:
    build: ./recipe/service
    container_name: recipe-service
    depends_on:
      - recipe-cache
      - recipe-database
    volumes:
      - ./scripts:/opt
    links:
      - recipe-cache:cache
      - recipe-database:database
    networks:
      - services
      - recipe-service
  
  recipe-cache:
    image: redis:5.0.7
    container_name: recipe-cache
    volumes:
      - './recipe/cache:/data'
    restart: always
    networks:
      - recipe-service

  recipe-database:
    image: mysql:5.7.28
    container_name: recipe-database
    volumes:
      - './recipe/database:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - recipe-service
  
  #
  # ---- User service and related ----
  user-service:
    build: ./user/service
    container_name: user-service
    depends_on:
      - user-cache
      - user-database
    volumes:
      - ./scripts:/opt
    links:
      - user-cache:cache
      - user-database:database
    networks:
      - services
      - user-service
  
  user-cache:
    image: redis:5.0.7
    container_name: user-cache
    volumes:
      - './user/cache:/data'
    restart: always
    networks:
      - user-service

  user-database:
    image: mysql:5.7.28
    container_name: user-database
    ports:
      - 3306:3306
    volumes:
      - './user/database:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gluten
      MYSQL_USER: gluten
      MYSQL_PASSWORD: gluten
    networks:
      - user-service

networks:
  services:
  user-service:
  recipe-service:
